export const User_Loading = "User_Loading"
export const User_Loaded = "User_Loaded"
export const Auth_Error = "Auth_Error"
export const LogIn_Success = "LogIn_Success"
export const LogIn_Fail = "LogIn_Fail"
export const LogOut_Success = "LogOut_Success"
export const Register_Success = "Register_Success"
export const Register_Fail = "Register_Fail"